/*
 * Copyright 2025 crackn.co
 * SPDX-License-Identifier: Apache-2.0
 */

@file:OptIn(ExperimentalForeignApi::class, co.crackn.kompressor.ExperimentalKompressorApi::class)

package co.crackn.kompressor.video

import co.crackn.kompressor.image.ImageFormat
import co.crackn.kompressor.io.MediaDestination
import co.crackn.kompressor.io.MediaSource
import co.crackn.kompressor.testutil.Mp4Generator
import co.crackn.kompressor.testutil.OutputValidators
import co.crackn.kompressor.testutil.fileSize
import co.crackn.kompressor.testutil.readBytes
import kotlin.test.AfterTest
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.useContents
import kotlinx.coroutines.test.runTest
import platform.Foundation.NSFileManager
import platform.Foundation.NSTemporaryDirectory
import platform.Foundation.NSUUID
import platform.UIKit.UIImage

/**
 * End-to-end tests for [IosVideoCompressor.thumbnail] against real MP4 fixtures generated by
 * [Mp4Generator]. Covers the happy path (valid JPEG + correct dimensions), optional
 * `maxDimension` downscale, rotation preservation (`appliesPreferredTrackTransform = true`),
 * typed [VideoCompressionError] for out-of-range timestamps, and the `require()`
 * programmer-error contract.
 */
class VideoThumbnailIosTest {

    private lateinit var testDir: String
    private lateinit var inputPath: String
    private val compressor = IosVideoCompressor()

    @BeforeTest
    fun setUp() {
        testDir = NSTemporaryDirectory() + "kompressor-video-thumbnail-ios-${NSUUID().UUIDString}/"
        NSFileManager.defaultManager.createDirectoryAtPath(
            testDir, withIntermediateDirectories = true, attributes = null, error = null,
        )
        inputPath = Mp4Generator.generateMp4(
            outputPath = testDir + "input.mp4",
            width = INPUT_WIDTH,
            height = INPUT_HEIGHT,
            frameCount = INPUT_FRAME_COUNT,
            fps = INPUT_FPS,
        )
    }

    @AfterTest
    fun tearDown() {
        NSFileManager.defaultManager.removeItemAtPath(testDir, null)
    }

    @Test
    fun thumbnail_defaultArgs_producesValidJpegFrameAtZero() = runTest {
        val output = testDir + "thumb_default.jpg"

        val result = compressor.thumbnail(
            MediaSource.Local.FilePath(inputPath),
            MediaDestination.Local.FilePath(output),
        )

        assertTrue(result.isSuccess, "thumbnail() failed: ${result.exceptionOrNull()}")
        assertTrue(OutputValidators.isValidJpeg(readBytes(output)), "Output must be a valid JPEG")
        val compression = result.getOrThrow()
        assertEquals(fileSize(inputPath), compression.inputSize)
        assertEquals(fileSize(output), compression.outputSize)
        assertTrue(compression.durationMs >= 0)

        val image = checkNotNull(UIImage.imageWithContentsOfFile(output)) { "UIImage decode failed" }
        image.size.useContents {
            assertEquals(INPUT_WIDTH, width.toInt(), "Thumbnail must keep source width by default")
            assertEquals(INPUT_HEIGHT, height.toInt(), "Thumbnail must keep source height by default")
        }
    }

    @Test
    fun thumbnail_maxDimensionCapsLongerEdge() = runTest {
        val output = testDir + "thumb_scaled.jpg"

        val result = compressor.thumbnail(
            MediaSource.Local.FilePath(inputPath),
            MediaDestination.Local.FilePath(output),
            maxDimension = MAX_DIM,
        )

        assertTrue(result.isSuccess, "thumbnail() failed: ${result.exceptionOrNull()}")
        val image = checkNotNull(UIImage.imageWithContentsOfFile(output))
        image.size.useContents {
            val longer = maxOf(width, height).toInt()
            assertTrue(
                longer <= MAX_DIM,
                "Longer edge $longer must be <= $MAX_DIM (got ${width.toInt()}x${height.toInt()})",
            )
            val aspect = INPUT_WIDTH.toDouble() / INPUT_HEIGHT
            val outAspect = width / height
            assertTrue(kotlin.math.abs(aspect - outAspect) < ASPECT_TOLERANCE)
        }
    }

    @Test
    fun thumbnail_portraitFixture_producesPortraitThumbnail() = runTest {
        val portraitInput = Mp4Generator.generateMp4(
            outputPath = testDir + "portrait.mp4",
            width = INPUT_WIDTH,
            height = INPUT_HEIGHT,
            frameCount = INPUT_FRAME_COUNT,
            rotationDegrees = PORTRAIT_ROTATION,
        )
        val output = testDir + "thumb_portrait.jpg"

        val result = compressor.thumbnail(
            MediaSource.Local.FilePath(portraitInput),
            MediaDestination.Local.FilePath(output),
        )

        assertTrue(result.isSuccess, "thumbnail() failed: ${result.exceptionOrNull()}")
        val image = checkNotNull(UIImage.imageWithContentsOfFile(output))
        // Source is landscape buffer tagged rotate-90 so the displayed frame is portrait —
        // `appliesPreferredTrackTransform = true` must honour that and produce a portrait
        // CGImage.
        image.size.useContents {
            assertTrue(
                height > width,
                "Portrait thumbnail must have height > width (got ${width.toInt()}x${height.toInt()})",
            )
        }
    }

    @Test
    fun thumbnail_atMillisExceedsDuration_returnsTimestampOutOfRange() = runTest {
        val output = testDir + "thumb_overshoot.jpg"
        // Fixture is 30 frames at 30fps ≈ 1 s. Anything past 10 s is definitely out of range.
        val result = compressor.thumbnail(
            MediaSource.Local.FilePath(inputPath),
            MediaDestination.Local.FilePath(output),
            atMillis = OVERSHOOT_MILLIS,
        )

        assertTrue(result.isFailure)
        val error = result.exceptionOrNull()
        assertTrue(
            error is VideoCompressionError.TimestampOutOfRange,
            "Expected TimestampOutOfRange, got ${error?.let { it::class.simpleName }}: $error",
        )
        // Partial output must not leak — `deletingOutputOnFailure` is the guard.
        assertTrue(
            !NSFileManager.defaultManager.fileExistsAtPath(output),
            "Output file must be deleted on failure",
        )
    }

    @Test
    fun thumbnail_negativeAtMillis_throwsIllegalArgumentException() = runTest {
        assertFailsWith<IllegalArgumentException> {
            compressor.thumbnail(
                MediaSource.Local.FilePath(inputPath),
                MediaDestination.Local.FilePath(testDir + "never.jpg"),
                atMillis = -1L,
            )
        }
    }

    @Test
    fun thumbnail_qualityOutOfRange_throwsIllegalArgumentException() = runTest {
        assertFailsWith<IllegalArgumentException> {
            compressor.thumbnail(
                MediaSource.Local.FilePath(inputPath),
                MediaDestination.Local.FilePath(testDir + "never.jpg"),
                quality = INVALID_QUALITY,
            )
        }
    }

    @Test
    fun thumbnail_nonPositiveMaxDimension_throwsIllegalArgumentException() = runTest {
        assertFailsWith<IllegalArgumentException> {
            compressor.thumbnail(
                MediaSource.Local.FilePath(inputPath),
                MediaDestination.Local.FilePath(testDir + "never.jpg"),
                maxDimension = 0,
            )
        }
    }

    @Test
    fun thumbnail_webpFormat_isRejectedAsUnsupportedOnIos() = runTest {
        val output = testDir + "thumb.webp"

        val result = compressor.thumbnail(
            MediaSource.Local.FilePath(inputPath),
            MediaDestination.Local.FilePath(output),
            format = ImageFormat.WEBP,
        )

        assertTrue(result.isFailure, "WEBP must be rejected on iOS")
        val error = result.exceptionOrNull()
        assertTrue(
            error is VideoCompressionError.EncodingFailed,
            "Expected EncodingFailed (remapped from UnsupportedOutputFormat), " +
                "got ${error?.let { it::class.simpleName }}: $error",
        )
    }

    private companion object {
        const val INPUT_WIDTH = 320
        const val INPUT_HEIGHT = 240
        const val INPUT_FRAME_COUNT = 30
        const val INPUT_FPS = 30
        const val MAX_DIM = 120
        const val ASPECT_TOLERANCE = 0.05
        const val PORTRAIT_ROTATION = 90
        const val OVERSHOOT_MILLIS = 10_000L
        const val INVALID_QUALITY = 150
    }
}
