/*
 * Copyright 2025 crackn.co
 * SPDX-License-Identifier: Apache-2.0
 */

@file:OptIn(ExperimentalForeignApi::class, co.crackn.kompressor.ExperimentalKompressorApi::class)

package co.crackn.kompressor.video

import co.crackn.kompressor.audio.AudioCompressionConfig
import co.crackn.kompressor.audio.IosAudioCompressor
import co.crackn.kompressor.image.ImageFormat
import co.crackn.kompressor.io.MediaDestination
import co.crackn.kompressor.io.MediaSource
import co.crackn.kompressor.io.of
import co.crackn.kompressor.testutil.Mp4Generator
import co.crackn.kompressor.testutil.OutputValidators
import co.crackn.kompressor.testutil.WavGenerator
import co.crackn.kompressor.testutil.fileSize
import co.crackn.kompressor.testutil.readBytes
import co.crackn.kompressor.testutil.writeBytes
import kotlin.test.AfterTest
import kotlin.test.BeforeTest
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertFailsWith
import kotlin.test.assertTrue
import kotlinx.cinterop.ExperimentalForeignApi
import kotlinx.cinterop.useContents
import kotlinx.coroutines.test.runTest
import okio.Buffer
import platform.AVFoundation.AVURLAsset
import platform.AVFoundation.duration
import platform.CoreMedia.CMTimeGetSeconds
import platform.Foundation.NSFileManager
import platform.Foundation.NSTemporaryDirectory
import platform.Foundation.NSURL
import platform.Foundation.NSUUID
import platform.UIKit.UIImage

/**
 * End-to-end tests for [IosVideoCompressor.thumbnail] against real MP4 fixtures generated by
 * [Mp4Generator]. Covers the happy path (valid JPEG + correct dimensions), optional
 * `maxDimension` downscale, rotation preservation (`appliesPreferredTrackTransform = true`),
 * typed [VideoCompressionError] for out-of-range timestamps, and the `require()`
 * programmer-error contract.
 */
class VideoThumbnailIosTest {

    private lateinit var testDir: String
    private lateinit var inputPath: String
    private val compressor = IosVideoCompressor()

    @BeforeTest
    fun setUp() {
        testDir = NSTemporaryDirectory() + "kompressor-video-thumbnail-ios-${NSUUID().UUIDString}/"
        NSFileManager.defaultManager.createDirectoryAtPath(
            testDir, withIntermediateDirectories = true, attributes = null, error = null,
        )
        inputPath = Mp4Generator.generateMp4(
            outputPath = testDir + "input.mp4",
            width = INPUT_WIDTH,
            height = INPUT_HEIGHT,
            frameCount = INPUT_FRAME_COUNT,
            fps = INPUT_FPS,
        )
    }

    @AfterTest
    fun tearDown() {
        NSFileManager.defaultManager.removeItemAtPath(testDir, null)
    }

    @Test
    fun thumbnail_defaultArgs_producesValidJpegFrameAtZero() = runTest {
        val output = testDir + "thumb_default.jpg"

        val result = compressor.thumbnail(
            MediaSource.Local.FilePath(inputPath),
            MediaDestination.Local.FilePath(output),
        )

        assertTrue(result.isSuccess, "thumbnail() failed: ${result.exceptionOrNull()}")
        assertTrue(OutputValidators.isValidJpeg(readBytes(output)), "Output must be a valid JPEG")
        val compression = result.getOrThrow()
        assertEquals(fileSize(inputPath), compression.inputSize)
        assertEquals(fileSize(output), compression.outputSize)
        assertTrue(compression.durationMs >= 0)

        val image = checkNotNull(UIImage.imageWithContentsOfFile(output)) { "UIImage decode failed" }
        image.size.useContents {
            assertEquals(INPUT_WIDTH, width.toInt(), "Thumbnail must keep source width by default")
            assertEquals(INPUT_HEIGHT, height.toInt(), "Thumbnail must keep source height by default")
        }
    }

    @Test
    fun thumbnail_maxDimensionCapsLongerEdge() = runTest {
        val output = testDir + "thumb_scaled.jpg"

        val result = compressor.thumbnail(
            MediaSource.Local.FilePath(inputPath),
            MediaDestination.Local.FilePath(output),
            maxDimension = MAX_DIM,
        )

        assertTrue(result.isSuccess, "thumbnail() failed: ${result.exceptionOrNull()}")
        val image = checkNotNull(UIImage.imageWithContentsOfFile(output))
        image.size.useContents {
            val longer = maxOf(width, height).toInt()
            assertTrue(
                longer <= MAX_DIM,
                "Longer edge $longer must be <= $MAX_DIM (got ${width.toInt()}x${height.toInt()})",
            )
            val aspect = INPUT_WIDTH.toDouble() / INPUT_HEIGHT
            val outAspect = width / height
            assertTrue(kotlin.math.abs(aspect - outAspect) < ASPECT_TOLERANCE)
        }
    }

    @Test
    fun thumbnail_portraitFixture_producesPortraitThumbnail() = runTest {
        val portraitInput = Mp4Generator.generateMp4(
            outputPath = testDir + "portrait.mp4",
            width = INPUT_WIDTH,
            height = INPUT_HEIGHT,
            frameCount = INPUT_FRAME_COUNT,
            rotationDegrees = PORTRAIT_ROTATION,
        )
        val output = testDir + "thumb_portrait.jpg"

        val result = compressor.thumbnail(
            MediaSource.Local.FilePath(portraitInput),
            MediaDestination.Local.FilePath(output),
        )

        assertTrue(result.isSuccess, "thumbnail() failed: ${result.exceptionOrNull()}")
        val image = checkNotNull(UIImage.imageWithContentsOfFile(output))
        // Source is landscape buffer tagged rotate-90 so the displayed frame is portrait —
        // `appliesPreferredTrackTransform = true` must honour that and produce a portrait
        // CGImage.
        image.size.useContents {
            assertTrue(
                height > width,
                "Portrait thumbnail must have height > width (got ${width.toInt()}x${height.toInt()})",
            )
        }
    }

    @Test
    fun thumbnail_atMillisExceedsDuration_returnsTimestampOutOfRange() = runTest {
        val output = testDir + "thumb_overshoot.jpg"
        // Fixture is 30 frames at 30fps ≈ 1 s. Anything past 10 s is definitely out of range.
        val result = compressor.thumbnail(
            MediaSource.Local.FilePath(inputPath),
            MediaDestination.Local.FilePath(output),
            atMillis = OVERSHOOT_MILLIS,
        )

        assertTrue(result.isFailure)
        val error = result.exceptionOrNull()
        assertTrue(
            error is VideoCompressionError.TimestampOutOfRange,
            "Expected TimestampOutOfRange, got ${error?.let { it::class.simpleName }}: $error",
        )
        // Partial output must not leak — `deletingOutputOnFailure` is the guard.
        assertTrue(
            !NSFileManager.defaultManager.fileExistsAtPath(output),
            "Output file must be deleted on failure",
        )
    }

    @Test
    fun thumbnail_negativeAtMillis_throwsIllegalArgumentException() = runTest {
        assertFailsWith<IllegalArgumentException> {
            compressor.thumbnail(
                MediaSource.Local.FilePath(inputPath),
                MediaDestination.Local.FilePath(testDir + "never.jpg"),
                atMillis = -1L,
            )
        }
    }

    @Test
    fun thumbnail_qualityOutOfRange_throwsIllegalArgumentException() = runTest {
        assertFailsWith<IllegalArgumentException> {
            compressor.thumbnail(
                MediaSource.Local.FilePath(inputPath),
                MediaDestination.Local.FilePath(testDir + "never.jpg"),
                quality = INVALID_QUALITY,
            )
        }
    }

    @Test
    fun thumbnail_nonPositiveMaxDimension_throwsIllegalArgumentException() = runTest {
        assertFailsWith<IllegalArgumentException> {
            compressor.thumbnail(
                MediaSource.Local.FilePath(inputPath),
                MediaDestination.Local.FilePath(testDir + "never.jpg"),
                maxDimension = 0,
            )
        }
    }

    @Test
    fun thumbnail_webpFormat_isRejectedAsUnsupportedOnIos() = runTest {
        val output = testDir + "thumb.webp"

        val result = compressor.thumbnail(
            MediaSource.Local.FilePath(inputPath),
            MediaDestination.Local.FilePath(output),
            format = ImageFormat.WEBP,
        )

        assertTrue(result.isFailure, "WEBP must be rejected on iOS")
        val error = result.exceptionOrNull()
        assertTrue(
            error is VideoCompressionError.EncodingFailed,
            "Expected EncodingFailed (remapped from UnsupportedOutputFormat), " +
                "got ${error?.let { it::class.simpleName }}: $error",
        )
    }

    @Test
    fun thumbnail_audioOnlyM4a_returnsUnsupportedSourceFormat() = runTest {
        // Parity with `compress()`'s `validateHasVideoTrack` pre-flight: audio-only inputs must
        // surface the same `VideoCompressionError.UnsupportedSourceFormat` through both
        // `compress()` and `thumbnail()`. Without the pre-flight guard the call surfaces
        // `DecodingFailed` from `AVAssetImageGenerator.copyCGImageAtTime` instead — invisible
        // to consumers `when`-branching on the typed hierarchy.
        val audioOnly = createAudioOnlyM4a()
        val output = testDir + "thumb_audio_only.jpg"

        val result = compressor.thumbnail(
            MediaSource.Local.FilePath(audioOnly),
            MediaDestination.Local.FilePath(output),
        )

        assertTrue(result.isFailure, "Audio-only m4a must be rejected")
        val error = result.exceptionOrNull()
        assertTrue(
            error is VideoCompressionError.UnsupportedSourceFormat,
            "Expected UnsupportedSourceFormat, got ${error?.let { it::class.simpleName }}: $error",
        )
        assertTrue(
            !NSFileManager.defaultManager.fileExistsAtPath(output),
            "No partial output should leak on failure",
        )
    }

    @Test
    fun thumbnail_atMillisEqualsDuration_succeeds() = runTest {
        // Boundary check: the implementation uses strict `>` comparison, so `atMillis == duration`
        // must succeed (last frame of a 1s fixture is at the duration boundary). Reading the
        // fixture's actual probed duration via `CMTimeGetSeconds(asset.duration)` keeps the
        // test self-contained — the encoder's 30-frames-at-30fps doesn't always produce
        // exactly 1000 ms in the container.
        val durationMs = readDurationMillis(inputPath)
        val output = testDir + "thumb_boundary.jpg"

        val result = compressor.thumbnail(
            MediaSource.Local.FilePath(inputPath),
            MediaDestination.Local.FilePath(output),
            atMillis = durationMs,
        )

        assertTrue(
            result.isSuccess,
            "atMillis == duration ($durationMs) must succeed: ${result.exceptionOrNull()}",
        )
        assertTrue(OutputValidators.isValidJpeg(readBytes(output)), "Output must be a valid JPEG")
    }

    @Test
    fun thumbnail_atMillisEqualsDurationPlusOne_returnsTimestampOutOfRange() = runTest {
        // Boundary check: any value strictly greater than the probed duration must trip the `>`
        // guard and produce `TimestampOutOfRange`. Pairs with the equal-to-duration test above to
        // lock the strict-inequality contract against off-by-one regressions.
        // We use `+ DURATION_OVERSHOOT_MILLIS` (100 ms) rather than `+ 1` so the test stays
        // robust against `CMTimeGetSeconds(asset.duration) → toLong()` quantisation drift across
        // AVFoundation builds — the contract being tested is "strictly greater than duration",
        // not "millisecond-exact off-by-one", and 100 ms is well under any real fixture's length.
        val durationMs = readDurationMillis(inputPath)
        val output = testDir + "thumb_boundary_overshoot.jpg"

        val result = compressor.thumbnail(
            MediaSource.Local.FilePath(inputPath),
            MediaDestination.Local.FilePath(output),
            atMillis = durationMs + DURATION_OVERSHOOT_MILLIS,
        )

        assertTrue(result.isFailure, "atMillis == duration + 1 must fail")
        val error = result.exceptionOrNull()
        assertTrue(
            error is VideoCompressionError.TimestampOutOfRange,
            "Expected TimestampOutOfRange, got ${error?.let { it::class.simpleName }}: $error",
        )
        assertTrue(
            !NSFileManager.defaultManager.fileExistsAtPath(output),
            "No partial output should leak on failure",
        )
    }

    @Test
    fun thumbnail_bytesInput_matchesFilePathOutcome() = runTest {
        // Mirrors the Stream sibling below for the `MediaSource.Local.Bytes` materialization
        // path. `Bytes` flows through `resolveStreamOrBytesToTempFile` to a temp file, then
        // through the same `thumbnailFilePath` pipeline as the FilePath-based call. Bitwise
        // equality holds because the JPEG re-encode through `writeUIImageToFile` is
        // deterministic (no AVFoundation wall-clock timestamps in the still-image output).
        val inputBytes = readBytes(inputPath)
        val legacyPath = testDir + "legacy_bytes.jpg"
        val bytesPath = testDir + "bytes_bytes.jpg"

        val legacy = compressor.thumbnail(
            MediaSource.Local.FilePath(inputPath),
            MediaDestination.Local.FilePath(legacyPath),
        )
        val bytes = compressor.thumbnail(
            MediaSource.Local.Bytes(inputBytes),
            MediaDestination.Local.FilePath(bytesPath),
        )

        assertTrue(legacy.isSuccess, "legacy thumbnail() failed: ${legacy.exceptionOrNull()}")
        assertTrue(bytes.isSuccess, "bytes thumbnail() failed: ${bytes.exceptionOrNull()}")
        assertTrue(
            readBytes(bytesPath).contentEquals(readBytes(legacyPath)),
            "Bytes input must produce byte-identical output to legacy FilePath",
        )
    }

    @Test
    fun thumbnail_fileUrlInput_producesValidJpegFrame() = runTest {
        // Exercises the `MediaSource.of(NSURL)` builder with a `file://` URL — the
        // `IosUrlMediaSource` resolver unwraps to `NSURL.path` (no temp materialization for
        // `file://`). Locks the file-URL → `thumbnailFilePath` handoff so a regression in the
        // URL resolver wouldn't ship silently behind the FilePath-only test matrix.
        val output = testDir + "thumb_url.jpg"
        val fileUrl = NSURL.fileURLWithPath(inputPath)

        val result = compressor.thumbnail(
            MediaSource.of(fileUrl),
            MediaDestination.Local.FilePath(output),
        )

        assertTrue(result.isSuccess, "thumbnail(file://) failed: ${result.exceptionOrNull()}")
        assertTrue(OutputValidators.isValidJpeg(readBytes(output)), "Output must be a valid JPEG")
        val image = checkNotNull(UIImage.imageWithContentsOfFile(output))
        image.size.useContents {
            assertEquals(INPUT_WIDTH, width.toInt(), "Thumbnail must keep source width by default")
            assertEquals(INPUT_HEIGHT, height.toInt(), "Thumbnail must keep source height by default")
        }
    }

    @Test
    fun thumbnail_streamInput_matchesFilePathOutcome() = runTest {
        // Locks the `Stream` → `materializeToTempFile` → `thumbnailFilePath` handoff so a
        // regression in the materializer (e.g. early-EOF, wrong content-length) wouldn't ship
        // silently behind the FilePath-only test matrix. JPEG re-encode through
        // `writeUIImageToFile` is deterministic, so bitwise comparison holds (no AVFoundation
        // wall-clock timestamps in the still-image output, unlike the audio/video sibling).
        val inputBytes = readBytes(inputPath)
        val legacyPath = testDir + "legacy_stream.jpg"
        val streamPath = testDir + "stream_stream.jpg"

        val legacy = compressor.thumbnail(
            MediaSource.Local.FilePath(inputPath),
            MediaDestination.Local.FilePath(legacyPath),
        )
        val stream = compressor.thumbnail(
            MediaSource.Local.Stream(
                Buffer().apply { write(inputBytes) },
                sizeHint = inputBytes.size.toLong(),
            ),
            MediaDestination.Local.FilePath(streamPath),
        )

        assertTrue(legacy.isSuccess, "legacy thumbnail() failed: ${legacy.exceptionOrNull()}")
        assertTrue(stream.isSuccess, "stream thumbnail() failed: ${stream.exceptionOrNull()}")
        assertTrue(
            readBytes(streamPath).contentEquals(readBytes(legacyPath)),
            "Stream input must produce byte-identical output to legacy FilePath",
        )
    }

    /**
     * Builds an audio-only m4a fixture by round-tripping a generated WAV through
     * [IosAudioCompressor]. Round-trip avoids shipping a binary asset and keeps the test
     * self-contained — the resulting m4a has an audio track only, which is what the audio-only
     * thumbnail rejection test needs to exercise the `validateHasVideoTrack` pre-flight.
     */
    private suspend fun createAudioOnlyM4a(): String {
        val wavPath = testDir + "audio_in.wav"
        writeBytes(
            wavPath,
            WavGenerator.generateWavBytes(
                durationSeconds = AUDIO_FIXTURE_SECONDS,
                sampleRate = WAV_SAMPLE_RATE,
                channels = WAV_CHANNELS,
            ),
        )
        val m4aPath = testDir + "audio_only.m4a"
        val res = IosAudioCompressor().compress(
            MediaSource.Local.FilePath(wavPath),
            MediaDestination.Local.FilePath(m4aPath),
            AudioCompressionConfig(),
        )
        check(res.isSuccess) { "audio fixture generation failed: ${res.exceptionOrNull()}" }
        return m4aPath
    }

    /**
     * Reads the fixture's actual container duration via `CMTimeGetSeconds(asset.duration)` so the
     * boundary tests can probe `atMillis == duration` without relying on encoder math
     * (frames × fps doesn't always equal exact container duration).
     */
    private fun readDurationMillis(path: String): Long {
        val asset = AVURLAsset(uRL = NSURL.fileURLWithPath(path), options = null)
        val durationSec = CMTimeGetSeconds(asset.duration)
        check(durationSec.isFinite() && durationSec > 0) { "Fixture has no readable duration: $path" }
        return (durationSec * MILLIS_PER_SECOND).toLong()
    }

    private companion object {
        const val INPUT_WIDTH = 320
        const val INPUT_HEIGHT = 240
        const val INPUT_FRAME_COUNT = 30
        const val INPUT_FPS = 30
        const val MAX_DIM = 120
        const val ASPECT_TOLERANCE = 0.05
        const val PORTRAIT_ROTATION = 90
        const val OVERSHOOT_MILLIS = 10_000L
        const val INVALID_QUALITY = 150
        const val AUDIO_FIXTURE_SECONDS = 1
        const val WAV_SAMPLE_RATE = 44_100
        const val WAV_CHANNELS = 2
        const val MILLIS_PER_SECOND = 1000.0
        const val DURATION_OVERSHOOT_MILLIS = 100L
    }
}
